---
title: ''
output: word_document
bibliography: Zotero_references.bib #This can be generated by exporting BibTex file from Zotero
csl: new-phytologist.csl 

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Dear Editor:

Below please find our responses to the editorial requests for our manuscript 'Thermal sensitivity across forest vertical profiles: patterns, mechanisms, and ecological implications' NPH-TR-2021-38020.R2. We have addressed all points, as detailed below.

Sincerely,

Nidhi Vinod & Kristina Anderson-Teixeira (on behalf of all coauthors)

\newpage

# Response to Editorial Requests

## 1)      Main text

Please make the following changes to the main text + tables file and then upload your final file in Word format:

a) Title page:

•       Tyeen C. Taylor appears in ScholarOne as ‘Tyeen Taylor’ and Kristina J. Anderson-Teixeira appears in ScholarOne as ‘Kristina Anderson-Teixeira’. Please ensure that the names appear as you wish for publication in the main text file.

•       Insert postal/ZIP code for the author affiliation number 3 listed on the paper.

•       Insert the ORCID details for the authors listed on the paper (where available).

•       Insert any individual or lab-associated social media accounts (e.g. Twitter, Facebook, Instagram, WeChat etc.), if available, which can be used for social media promotion of your article. (Note, this information will not appear in your published paper.)

b) I note that one author (Thomas Buckley) was added to the paper between revisions. It is unusual for authorship of an article to change during the revision stages, and it is journal policy that we seek the approval of all the authors on the paper for any such changes. Please clarify this change to the authorship of your paper and provide reasons for why this author has now been included. Once this has been supplied, I will contact your co-authors to obtain their approval for this change (as per journal policy).

c) Acknowledgements: please check your Acknowledgements section to ensure that details of funding bodies and grant numbers are complete and correct.

d) Author contributions: please insert the individual contributions for Martijn Slot, Tyeen C. Taylor, Lawren Sack and Thomas N. Buckley (as has been done for other authors on the paper), as it is journal style that the initials of each author should appear in section to acknowledge their contribution to the work.

e) Data availability section: amend the wording ‘The R scripts used for new analyses are (will be) available via GitHub (https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEcoClimLab%2Fvertical-thermal-review&amp;data=05%7C01%7CTeixeiraK%40si.edu%7Ca48e6afee6224253138208da7528be6f%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637951116144876893%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=ujAgGxmh7t64HbF5ZDuTe4%2F9fWNaww80PaYZXcMZDn8%3D&amp;reserved=0) and archived in Zenodo (DOI: [TBD])’. Ensure that the GitHub link is live and that the Zenodo DOI is added (to assist readers).

f) References:

•       Ensure article titles are given in the References section in journal style (e.g. Latin/gene names appropriately italicised; subscript/superscript characters).

•       Atherton et al. (2017), Bertrand et al. (2020), Christoffersen et al. (2016), Doughty & Goulden (2008), Feeley et al. (2020), Krinner et al. (2005), Muir (2019), Scheffers et al. (2013): add the page ranges for these journal articles.

•       Bennett et al. (2021), Garcia (2021), Monson et al. (2021), Niinemets et al. (2015b): insert volume number and page range for these references.

•       Carter & Cavaleri (2018), Chen et al. (2020): insert the article ID/page range for these references.

•       Bin et al. (2022), Heilman et al (2022): insert the doi for these journal articles (or if the information is available, the volume number and page range).

•       Burgess et al. (2006): please insert further information to aid the reader in accessing this citation (e.g. URL and date accessed, or publisher and place of publication).

•       Haberlandt (1914), McDowell et al. (2011): insert the place of publication (city, state (if US) and country) for these citations.

•       Harris & Medina (2013): insert the volume number.

•       IPCC (2021), Pörtner et al. (2021): please insert further information to aid the reader in accessing these citations (e.g. publisher, URL and date accessed, or publisher and place of publication).

•       Kesselmeier & Staudt: please add the year of publication as well as the page range.

•       Kunert (in press): please update the reference with the year and the article identifier or, if the information is available, the volume number and page range.

•       Lowman & Rinker (1995): insert the editors and the place of publication (city, state (if US) and country) for this book chapter citation.

•       Piponiot et al. (2022): this paper has now been published in an issue of New Phytologist. Please update this citation with the following volume number and page range: 234: 5.

•       Slot et al. (2021b): if the information is available, update the article identifier with the volume number and page range.

g) Figure legends:

•       Fig. 4: please amend the spelling of ‘Tailand’ in the top panel of the figure.

•       Fig. 5(a): please add text to the legend to explain the meaning of the different thickness of arrows used (if this is significant).

•       Fig. 5(b): please amend ‘in press’ to ‘2022’ in the last line of the legend.

h) Table legends:

•       I notice that the tables are pasted into the main text file as graphics and, unfortunately it is not possible to typeset the tables from this format. Insert the two tables in editable form in the main text file or upload separate Excel files.

•       Table 1: please add text to the table footnote to explain the meaning of ‘TrS’, as has been done for TrB, TeB, TeN and BoN.

•       Table 2: the references presented in the right-most column are given twice at the end of the table. Please remove one set of this duplicated information. The footnote also includes the text ‘** composite climatic stress variable integrating temperature, vapour pressure deficit, and relative humidity is higher in lower canopy’ however I cannot see ‘**’ in the table (my apologies if I have missed it). Please check.

## 2)      Figs 1–6

Please delete the figures from the main manuscript (retaining the figure legends in the main text file) and then upload new high-resolution files for the figures.

Please note that a professional illustrator will work on your figures, and so the figures will need to be in an editable format. To minimise publication time of your manuscript and help you achieve the optimum quality for your published figures it is important that all electronic artwork is supplied in the correct format and resolution. Please upload the original working files for the figures – this greatly facilitates the job of the illustrator when working on your figures. Line art (e.g. charts, graphs and illustrations) should be generated in a vector program and saved in EPS format at 600 dpi (other vector formats such as .ps, .ai and .pdf are also OK). Half-tones (e.g. photographs) should be saved in TIFF format at 300 dpi. Figures containing a combination of photographic images and text should be saved as EPS or PDF and any photographic images embedded within these files should be at least 300 dpi. Please also send a copy of the embedded image as a separate file.

Figures can also be set from other formats including PowerPoint; please send the original working file or export it to PDF format (exporting the file to TIFF will flatten the artwork and make it noneditable).

Let me know if there are any important elements (colours, layout and spacing, symbols etc) of the figures that should be retained and if you have specific instructions that you would like the Illustrator to take on board.

- **It will generally be fine to adjust colors, layout, and spacing on the figures.**

- **We would like to retain the background painting in Figure 1 (by the lead author)**

I confirm that Figs 1–6 will appear in colour in the published article.

**Okay.**

## 3)      Supporting Information (Fig. S1, Methods S1–S3, Notes S1 and Table S1 – uploaded as as a separate Word file)

Please address the following points.

•       Title page: insert the author names (but not the superscript numbers/symbols or affiliations) and the article acceptance date: 31 July 2022.

•       Title page and page 2: please relabel ‘Note S1’ to ‘Notes S1’, for journal style and amend the main text citations accordingly.

•       Methods S1: please insert to the references section the full reference for the R Core Team citation given in Methods S1 (page 4).

•       Please add the full refence for this citation to the refence list at the end of the file.

•       Fig. S1: the figure includes panels (a)–(e). Please add a mention to each panel to the figure legend.

•       References section: Doughty & Goulden (2008), Muir (2019): add the page ranges for these journal articles.

•       National Ecological Observatory Network (NEON) (2022b, 2022a, 2022c, 2022d, 2022e): please include URL and date accessed for these references, to aid the reader.

•       Convert your final Supporting Information file provided as a Word file to PDF format. We recommend that you scan through the PDF to ensure that all is correct before uploading this file (this is the final file that will be published on Wiley Online Library).

## 4)      Permissions

Please address the following point.

•       Fig. 5(a): the legend notes that the figure is from Kunert et al. (2017). Please check the permissions policy of ‘Agricultural and Forest Meteorology’ regarding reusing published figures and then either send me a copy of the permission granted to adapt the figure, or confirm that permission is not required.

## 5) Licence/copyright form: 
please note that you will be contacted by the publisher in due course regarding the licence/copyright form for your article. Once your article has been received by Wiley for production you will receive an email from Wiley’s Author Services system which will ask you to log in and will present you with the appropriate license for completion. If you have any questions, please do not hesitate to get in touch with us directly. Note, your article cannot be published until the publisher has received the appropriate signed license agreement.

**Okay, we will deal with this promptly when received.**

## 6) Data Deposition
Finally, we remind authors that new sequence data should be deposited in the EMBL/GenBank/DDBJ Nucleotide Sequence Databases, and accession numbers should be included in the final publication. In addition, please note that New Phytologist requires authors to ensure that data integral to the paper is available to readers in a form which allows for verification and replication of the results in the paper. For full details please refer to the author guidelines: https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnph.onlinelibrary.wiley.com%2Fhub%2Fjournal%2F14698137%2Fabout%2Fauthor-guidelines&amp;data=05%7C01%7CTeixeiraK%40si.edu%7Ca48e6afee6224253138208da7528be6f%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637951116144876893%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=g2wQGlViohQQ%2BL9F6b9WoWkOsurgYVyF5Fd4yj%2Bcumk%3D&amp;reserved=0.




