---
title: " "

output: 
  pdf_document:
    fig_caption: yes

header-includes:  \usepackage{float}
                  \usepackage{caption}
                  \captionsetup[table]{font=footnotesize}
                  \captionsetup[figure]{font=footnotesize}
                  \captionsetup[figure]{labelformat=empty}
                  \captionsetup[table]{labelformat=empty}
                  
bibliography: references.bib #This can be generated by exporting BibTex file from Zotero
csl: new-phytologist.csl 

---

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
options(knitr.table.format = "latex")
```

```{r eval = TRUE, echo=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
traits_table <- read.csv("Lit_Review/traits_table.csv", stringsAsFactors = FALSE, check.names = FALSE)
kable(traits_table, caption = "Table 1. Summary of observed variation in thermally-relevant leaf traits with canopy height and/or between sun and shade leaves", format = "latex", booktabs = TRUE,  escape = F)%>%
  column_spec(1, width = "7cm") %>%
  column_spec(2, width = "2cm") %>%
  column_spec(3, width = "2cm") %>%
  column_spec(5, width = "3cm") %>%
  column_spec(6, width = "4cm") %>%
  pack_rows("Leaf anatomy and morphological traits", 1, 10, latex_gap_space = "1em", colnum = 4, hline_before = FALSE) %>%
  pack_rows("Leaf physiology and biochemical traits", 11, 17, latex_gap_space = "1em", colnum = 4, hline_before = FALSE) %>%
  kable_styling(latex_options = c("scale_down", "hold_position"), protect_latex = T) 
  #NOTE: REFERENCES for this table need to go in the nocite section of header in the main doc!!!
```


\newpage

```{r eval = TRUE, echo=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
metabolism_table <- read.csv("Lit_Review/metabolism_table.csv", stringsAsFactors = FALSE, check.names = FALSE)
kable(metabolism_table, caption = "Table 2. Summary of observed variation in leaf metabolism and thermal responses across the vertical gradient and/or between sun and shade leaves", format = "latex", booktabs = TRUE,  escape = F)%>%
  column_spec(1, width = "6cm") %>%
  column_spec(2, width = "2cm") %>%
  column_spec(6, width = "4cm") %>%
  pack_rows("Stomatal conductance", 1, 3, latex_gap_space = "1em", colnum = 1, hline_before = FALSE) %>%
  pack_rows("Photosynthesis", 4, 8, latex_gap_space = "1em", colnum = 1, hline_before = FALSE) %>%
  pack_rows("Respiration", 9, 14, latex_gap_space = "1em", colnum = 1, hline_before = FALSE) %>%
  pack_rows("VOC production", 15, 15, latex_gap_space = "1em", colnum = 1, hline_before = FALSE) %>%
  kable_styling(latex_options = c("scale_down", "hold_position"), protect_latex = T) 
  #NOTE: REFERENCES for this table need to go in the nocite section of header in the main doc!!!
```
*composite climatic stress variable from canopy temperature, vapour pressure deficit, and relative humidity is higher in lower canopy